# Meant to be used in conjunction (after) the main docker-compose.yml
# in development environment:
#
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  web:
    volumes:
      - .:/code
  celery:
    volumes:
      - .:/code
