version: "3.9"

services:
  # Single instance only.
  redis:
    image: redis

  # Single instance only.
  db:
    build:
      context: ops
      dockerfile: db.Dockerfile
      args:
        POSTGRES_DB: ${DB_NAME:?missing DB name}
        POSTGRES_USER: ${DB_NAME:?err}
        POSTGRES_PASSWORD: "${DB_SECRET:?missing DB secret (long random string)}"
    hostname: db
    environment:
      POSTGRES_DB: ${DB_NAME:?missing DB name}
      POSTGRES_USER: ${DB_NAME:?err}
      POSTGRES_PASSWORD: "${DB_SECRET:?missing DB secret (long random string)}"

  # Must be run once, pre deploy.
  # Built image is reused by "web" and "celery".
  web-precheck:
    restart: "on-failure:10" # Restart, typically if DB is not ready to accept connections yet
    build:
      context: .
      dockerfile: Dockerfile
    image: local/web-precheck:latest
    command:
      - /bin/sh
      - -c
      - |
        export SNAPSHOT=$$(git describe --abbrev=0) &&
        python manage.py migrate &&
        python manage.py check --deploy
    environment:
      PRIMARY_HOSTNAME: ${HOST:?err}
      DATASET_TMP_ROOT: "/data/datasets"
      DEBUG: ${DEBUG:-0}
      DJANGO_SECRET: "${DJANGO_SECRET:?err}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_NAME:?err}
      DB_NAME: ${DB_NAME:?err}
      DB_SECRET: ${DB_SECRET:?err}
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_NAME: ${SERVICE_NAME:?missing service name}
      CONTACT_EMAIL: ${CONTACT_EMAIL:?missing service name}
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - redis

  # Can be run in multiple instances.
  web:
    image: local/web-precheck:latest
    hostname: ${HOST:?err}
    command:
      - /bin/sh
      - -c
      - |
        export SNAPSHOT=$$(git describe --abbrev=0) &&
        ./wait-for-migrations.sh &&
        if [ "$DEBUG" = "1" ]; then
          python manage.py runserver 0.0.0.0:8000
        else
          python manage.py clear_cache &&
          hypercorn -b '0.0.0.0:8000' -w 1 bibxml.asgi:application
        fi
    ports:
      - "${PORT:?missing port to expose web service under}:8000"
    environment:
      PRIMARY_HOSTNAME: ${HOST:?missing main hostname (e.g., localhost for development)}
      INTERNAL_HOSTNAMES: "web"
      DEBUG: ${DEBUG:-0}
      DJANGO_SECRET: "${DJANGO_SECRET:?missing Django secret (long random string)}"
      API_SECRET: "${API_SECRET:?missing API secret}"
      EXTRA_API_SECRETS: "${EXTRA_API_SECRETS}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_NAME:?err}
      DB_NAME: ${DB_NAME:?err}
      DB_SECRET: "${DB_SECRET:?err}"
      SERVICE_NAME: ${SERVICE_NAME:?missing service name}
      CONTACT_EMAIL: ${CONTACT_EMAIL:?missing service name}
      SERVER_EMAIL: ${SERVER_EMAIL}
      SENTRY_DSN: ${SENTRY_DSN}
      MATOMO_URL: ${MATOMO_URL}
      MATOMO_SITE_ID: ${MATOMO_SITE_ID}
      MATOMO_TAG_MANAGER_CONTAINER: ${MATOMO_TAG_MANAGER_CONTAINER}
      DATATRACKER_CLIENT_ID: ${DATATRACKER_CLIENT_ID}
      DATATRACKER_CLIENT_SECRET: ${DATATRACKER_CLIENT_SECRET}
      PYTHONUNBUFFERED: 1

      # TODO: Some environment variables could be removed from web container, and only made available to celery
      DATASET_TMP_ROOT: "/data/datasets"
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - web-precheck

  # Single instance only.
  celery:
    image: local/web-precheck:latest
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        export SNAPSHOT=$$(git describe --abbrev=0) &&
        ./wait-for-migrations.sh &&
        celery -A management worker -l info -c 1
    environment:
      PRIMARY_HOSTNAME: ${HOST:?err}
      INTERNAL_HOSTNAMES: "celery"
      DATASET_TMP_ROOT: "/data/datasets"
      DEBUG: ${DEBUG:-0}
      DJANGO_SECRET: "${DJANGO_SECRET:?err}"
      EXTRA_API_SECRETS: "${EXTRA_API_SECRETS}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_NAME:?err}
      DB_NAME: ${DB_NAME:?err}
      DB_SECRET: ${DB_SECRET:?err}
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_NAME: ${SERVICE_NAME:?missing service name}
      CONTACT_EMAIL: ${CONTACT_EMAIL:?missing service name}
      SENTRY_DSN: ${SENTRY_DSN}
      PYTHONUNBUFFERED: 1
    depends_on:
      - web-precheck
      - redis
    ports:
      - "9080:9080"

  flower:
    image: mher/flower
    hostname: flower
    environment:
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
    depends_on:
      - celery
    ports:
      - "5555:5555"

  celery-exporter:
    image: danihodovic/celery-exporter
    command: "--broker-url=redis://redis:6379"
    depends_on:
      - redis
    ports:
      - "9081:9808"

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    build:
      context: ops
      dockerfile: prometheus.Dockerfile
      args:
        TARGET_HOSTS: "['web:8000', 'celery:9080', 'celery-exporter:9808']"
        HTTP_BASIC_USERNAME: "ietf"
        HTTP_BASIC_PASSWORD: "${API_SECRET:?missing API secret}"
        JOB_NAME: "bibxml-service"
    depends_on:
      - web
      - celery
      - celery-exporter
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    hostname: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "ietf"
      GF_SECURITY_ADMIN_PASSWORD: ${API_SECRET}
      SOURCE_NAME: BibXML’s Prometheus
      SOURCE: "http://prometheus:9090/"
      SOURCE_VERSION: 1
    volumes:
      - ./ops/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./ops/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./ops/grafana-dashboard-gui-usage.json:/etc/dashboards/bibxml/gui_usage.json
      - ./ops/grafana-dashboard-api-usage.json:/etc/dashboards/bibxml/api_usage.json
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
