apiVersion: v1
kind: Service
metadata:
  labels:
    app: ws
  name: ws-service
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    app: ws
status:
  loadBalancer: {}
