openapi: 3.1.0

info:
  title: IETF BibXML service
  description: |
    IETF BibXML service provides an open and public API for its users to fetch references from.
    NOTE: Not all 500 responses are currently provided per the spec, wrapped in JSON.
  contact:
    email: ietf-ribose@ribose.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1

servers:
- url: /

paths:
  /api/v1/ref/{dataset}/{ref_id}/:
    parameters:
    - name: dataset
      in: path
      description: Dataset ID.
      required: true
      schema:
        $ref: '#/components/schemas/AvailableDatasets'
    - name: ref_id
      in: path
      description: Standard reference
      required: true
      schema:
        type: string

    get:
      parameters:
      - name: format
        in: query
        description: |
          Format to return citation in.
          NOTE: if `bibxml` is requested, application/json response will still be returned;
          the JSON object will provide a JSON-escaped BibXML string (see response spec).
        schema:
          type: string
          default: relaton
          enum: [bibxml, relaton]
      summary: Get citation
      description: >
        Retrieve citation from given dataset by reference.
        For external datasets (currently, `doi`), this incurs an additional network request.
      operationId: getCitationByReferenceId

      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: string
                description: BibXML-formatted citation
            application/json:
              schema:
                $ref: '#/components/schemas/CitationDetailsResponse'

        404:
          description: reference not found in given dataset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/search:
    post:
      summary: Search citations
      description: Search citations across datasets.
      operationId: searchCitations
      requestBody:
        required: true
        description: Search query
        content:
          application/json:
            schema:
              type: object

      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CitationSearchResultResponse'

        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /public/rfc/{legacy_dataset}/reference.{ref_id}.xml:
    parameters:
    - name: legacy_dataset
      in: path
      description: Legacy dataset ID
      required: true
      schema:
        $ref: '#/components/schemas/AvailableLegacyDatasets'
    - name: ref_id
      in: path
      description: Standard reference
      required: true
      schema:
        type: string
    get:
      summary: Get citation by XML2RFC tools path
      description: Returned citation is always in BibXML format. This endpoint returns raw XML response.
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: string

        404:
          description: reference not found, or legacy dataset is not known
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:

  schemas:

    AvailableDatasets:
      type: string
      # TODO: Auto-generate available dataset list at deployment time?
      enum:
      - rfcs
      - ids
      - rfcsubseries
      - misc
      - w3c
      - 3gpp
      - ieee
      - iana
      - doi
      - nist
      description: |
        For up-to-date list of available datasets,
        see bibxml-data-* repositories under ietf-ribose GitHub organization.
        See also bibxml-indexer service README.

    AvailableLegacyDatasets:
      type: string
      enum:
      {% for ds_id in legacy_dataset_ids %}
      - {{ ds_id }}
      {% endfor %}
      description: |
        For up-to-date list of available datasets,
        see bibxml-data-* repositories under ietf-ribose GitHub organization.
        See also bibxml-indexer service README.

    CitationDetailsResponse:
      type: object
      properties:
        data:
          type: object
          $ref: '#/components/schemas/CitationObject'

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              description: Code for automatic error processing
            message:
              type: string
              description: Human readable error message

    CitationSearchResultResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CitationObject'

    # TODO:
    # need to verify structure
    CitationObject:
      type: object
      description: Citation in Relaton format
      properties:
        id:
          type: string
        date:
          type: object
          properties:
            type:
              type: string
            value:
              type: string
          #required:
          #- type
          #- value
        link:
          type: object
          properties:
            type:
              type: string
            content:
              type: string
          #required:
          #- type
          #- content
        type:
          type: string
        docid:
          type: array
          items:
            type: object
        place:
          type: string
        title:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              format:
                type: string
              script:
                type: string
              content:
                type: string
              language:
                type: string
            #required:
            #- type
            #- format
            #- script
            #- content
            #- language
        script:
          type: string
        doctype:
          type: string
        revdate:
          type: string
        contributor:
          type: object
          properties:
            role:
              type: string
            organization:
              type: object
              properties:
                name:
                  type: string
                abbreviation:
                  type: string
              #required:
              #- name
              #- abbreviation
          #required:
          #- role
          #- organization
      required:
      - docid
      - doctype
