global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: ${JOB_NAME}
  basic_auth:
    username: ${HTTP_BASIC_USERNAME}
    password: ${HTTP_BASIC_PASSWORD}
  static_configs:
  - targets: ${TARGET_HOSTS}
