name: Get_logs

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup kubeconfig
        env:
          EKS_CLUSTER_NAME: bibxml-test-cluster
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 1.23.6

      - name: Describe deployments
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          kubectl describe deployment web
          kubectl describe deployment celery

      - name: Get logs
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          kubectl logs $(kubectl get po | tr " " "\n" | grep web)
          kubectl logs $(kubectl get po | tr " " "\n" | grep celery)
